#!/system/bin/sh

detectsu=`ls /data/data`
[ -z "$detectsu" ] && echo "Must be superuser!" && exit

while true; do

echo
echo "leanKernel configurator"
echo "---"
echo "0) display current settings"
echo "1) set interactiveX screen_off_maxfreq"
echo "2) configure wake gesture control"
echo "3) set cpu boost"
echo "4) set charging led"
echo "5) set rgb control (advanced)"
echo "6) set rgb control (simple)"
echo
echo "9) check top 10 wake locks (ie. wakeup sources)"
echo
echo -n "please enter a number (or press enter to exit): "

read option

case $option in
0)
	echo
	echo "current settings"
	echo "----------------"
	echo -n "1) interactiveX screen off maxfreq: "
	value=`cat /sys/devices/system/cpu/cpufreq/interactive/screen_off_maxfreq`
	[ $value -gt 2600000 ] && echo "Disabled" || echo $value
	echo -n "2) wake gestures (stock dt2w - haptic dt2w - s2w): "
	sdt=`cat /sys/bus/i2c/devices/1-004a/tsp`
	hdt=`cat /sys/android_touch/doubletap2wake`
	s2w=`cat /sys/android_touch/sweep2wake`
	echo "$sdt - $hdt - $s2w"
	echo -n "3) cpu boost: "
	cat /sys/module/cpu_boost/parameters/cpuboost_enable
	echo -n "4) charging led: "
	value=`cat /sys/class/leds/charging/trigger`
 	case "$value" in
		*"[battery-charging]"*) echo "Enabled" ;;
		*) echo "Disabled" ;;
	esac
	echo -n "5) rgb control (red green blue): "
	cat /sys/devices/platform/kcal_ctrl.0/kcal
	echo
	;;
1)
	echo -n "Enter a number between 0 and 5 (0:650mhz,1:883mhz,2:1.2ghz,3:1.5ghz,4:2.2ghz/default,5:disable): "
	read value
	case $value in
	  0) FREQ=652800;;
	  1) FREQ=883200;;
	  2) FREQ=1267200;;
	  3) FREQ=1574400;;
	  4) FREQ=2265600;;
	  5) FREQ=2649600;;
	esac
	echo $FREQ > /data/data/leankernel/screen_off_maxfreq
	echo $FREQ > /sys/devices/system/cpu/cpufreq/interactive/screen_off_maxfreq
	echo "Done! (also will persist at boot)"
	;;
2)
	echo -n "Enter 1 for stock dt2w, 2 for haptic dt2w, 3 for s2w, 4 for both, 0 to disable all:"
	read value
	case $value in
	  1)
		echo 0 > /sys/android_touch/doubletap2wake
		rm -f /data/data/leankernel/doubletap2wake
		echo 0 > /sys/android_touch/sweep2wake
		rm -f /data/data/leankernel/sweep2wake
		echo AUTO > /sys/bus/i2c/devices/1-004a/tsp
		echo AUTO > /data/data/leankernel/tsp
		;;
	  2)
		echo OFF > /sys/bus/i2c/devices/1-004a/tsp
		rm -f /data/data/leankernel/tsp
		echo 0 > /sys/android_touch/sweep2wake
		rm -f /data/data/leankernel/sweep2wake
		echo 1 > /sys/android_touch/doubletap2wake
		echo 1 > /data/data/leankernel/doubletap2wake
		;;
	  3)
		echo OFF > /sys/bus/i2c/devices/1-004a/tsp
		rm -f /data/data/leankernel/tsp
		echo 0 > /sys/android_touch/doubletap2wake
		rm -f /data/data/leankernel/doubletap2wake
		echo 15 > /sys/android_touch/sweep2wake
		echo 15 > /data/data/leankernel/sweep2wake
		;;
	  4)
		echo OFF > /sys/bus/i2c/devices/1-004a/tsp
		rm -f /data/data/leankernel/tsp
		echo 1 > /sys/android_touch/doubletap2wake
		echo 1 > /data/data/leankernel/doubletap2wake
		echo 15 > /sys/android_touch/sweep2wake
		echo 15 > /data/data/leankernel/sweep2wake
		;;
	  0)
		echo OFF > /sys/bus/i2c/devices/1-004a/tsp
		rm -f /data/data/leankernel/tsp
		echo 0 > /sys/android_touch/sweep2wake
		rm -f /data/data/leankernel/sweep2wake
		echo 0 > /sys/android_touch/doubletap2wake
		rm -f /data/data/leankernel/doubletap2wake
		;;
	esac
	echo "Done! (also will persist at boot)"
	;;
3)
        echo -n "Enter Y to enable, N to disable cpu boost: "
        read value
        echo $value > /data/data/leankernel/cpuboost_enable
        echo $value > /sys/module/cpu_boost/parameters/cpuboost_enable
        echo "Done! (also will persist at boot)"
	;;
4)
        echo -n "Enter Y to enable, N to disable charging led: "
        read value
	if [ "$value" == "Y" ] || [ "$value" == "y" ]; then 
        	echo battery-charging > /data/data/leankernel/charging_led
		echo battery-charging > /sys/class/leds/charging/trigger
		echo 1 > /sys/class/leds/charging/max_brightness
	else
        	rm -f /data/data/leankernel/charging_led
		echo none > /sys/class/leds/charging/trigger
	fi
        echo "Done! (also will persist at boot)"
	;;
5)
        echo -n "Enter three values (red, green, blue) between 0-255 (default is 255 255 255):"
        read value
	if [ -n "$value" ]; then
		echo "$value" > /data/data/leankernel/kcal
		echo "$value" > /sys/devices/platform/kcal_ctrl.0/kcal
		echo 1 > /sys/devices/platform/kcal_ctrl.0/kcal_ctrl
		echo "Done! (also will persist at boot)"
	fi
	;;
6)
        echo -n "Enter 1 for reference(6500k), 2 for cool(7400k), 3 for stock(6250k):"
        read value
	case $value in
	  1) RGB="248 246 255";;
	  2) RGB="237 235 255";;
	  *) RGB="255 255 255";;
	esac
	echo "$RGB" > /data/data/leankernel/kcal
	echo "$RGB" > /sys/devices/platform/kcal_ctrl.0/kcal
	echo 1 > /sys/devices/platform/kcal_ctrl.0/kcal_ctrl
	echo "Done! (also will persist at boot)"
	;;
9)
	echo
	if [ -a /system/xbin/awk ]; then
		echo "1st column: total time wakeup source has been active."
		echo "2nd column: max time the source was continuously active"
		echo "-----"
		cat /sys/kernel/debug/wakeup_sources | grep -v wakeup_count \
		  | awk '{ printf "%-10s%-8s %s\n",int($7/1000),int($8/1000),$1 }' \
		  | sort -rn | head -10
	else
		echo "busybox required!"
	fi
	;;
*)
	exit
	;;
esac
echo
done
