#!/system/bin/sh

detectsu=`ls /data/data`
[ -z "$detectsu" ] && echo "Must be superuser!" && exit

while true; do

echo
echo "leanKernel configurator"
echo "---"
echo "0) display current settings"
echo "1) set screen_off_maxfreq"
echo "2) set mmc crc"
echo "3) set cpu boost"
echo "4) set charging led"
echo "5) set rgb control"
echo
echo -n "please enter a number (or press enter to exit): "

read option

case $option in
0)
	echo
	echo "current settings"
	echo "----------------"
	echo -n "1) screen off maxfreq: "
	value=`cat /sys/devices/system/cpu/cpufreq/interactive/screen_off_maxfreq`
	[ $value -gt 2600000 ] && echo "Disabled" || echo $value
	echo -n "2) mmc crc: "
	cat /sys/module/mmc_core/parameters/use_spi_crc
	echo -n "3) cpu boost: "
	cat /sys/module/cpu_boost/parameters/cpuboost_enable
	echo -n "4) charging led: "
	value=`cat /sys/class/leds/charging/trigger`
 	case "$value" in
		*"[battery-charging]"*) echo "Enabled" ;;
		*) echo "Disabled" ;;
	esac
	echo -n "5) rgb control (red greed blue): "
	cat /sys/devices/platform/kcal_ctrl.0/kcal
	echo
	;;
1)
	echo -n "Enter a number between 0 and 4 (0:650mhz,1:883mhz,2:1.2ghz/default,3:1.5ghz,4:disable): "
	read value
	case $value in
	  0) FREQ=652800;;
	  1) FREQ=883200;;
	  2) FREQ=1267200;;
	  3) FREQ=1574400;;
	  4) FREQ=2649600;;
	esac
	echo $FREQ > /data/data/leankernel/screen_off_maxfreq
	echo $FREQ > /sys/devices/system/cpu/cpufreq/interactive/screen_off_maxfreq
	echo "Done! (also will persist at boot)"
	;;
2)
	echo -n "Enter Y to enable, N to disable mmc crc: "
	read value
	echo $value > /data/data/leankernel/use_spi_crc
	echo $value > /sys/module/mmc_core/parameters/use_spi_crc
	echo "Done! (also will persist at boot)"
	;;
3)
        echo -n "Enter Y to enable, N to disable cpu boost: "
        read value
        echo $value > /data/data/leankernel/cpuboost_enable
        echo $value > /sys/module/cpu_boost/parameters/cpuboost_enable
        echo "Done! (also will persist at boot)"
	;;
4)
        echo -n "Enter Y to enable, N to disable charging led: "
        read value
	if [ "$value" == "Y" ] || [ "$value" == "y" ]; then 
        	echo battery-charging > /data/data/leankernel/charging_led
		echo battery-charging > /sys/class/leds/charging/trigger
		echo 1 > /sys/class/leds/charging/max_brightness
	else
        	rm -f /data/data/leankernel/charging_led
		echo none > /sys/class/leds/charging/trigger
	fi
        echo "Done! (also will persist at boot)"
	;;
5)
        echo -n "Enter three values (red, green, blue) between 0-255 (default is 255 255 255):"
        read value
	if [ -n "$value" ]; then
		echo "$value" > /data/data/leankernel/kcal
		echo "$value" > /sys/devices/platform/kcal_ctrl.0/kcal
		echo 1 > /sys/devices/platform/kcal_ctrl.0/kcal_ctrl
		echo "Done! (also will persist at boot)"
	fi
	;;
*)
	exit
	;;
esac
echo
done
